version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: ExpenssoDB
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5434:5432"
    networks:
      - network

networks:
  network:
    driver: bridge